# Generated by Django 4.2 on 2023-05-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swan_page', '0003_partner_realisation_team_testimony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
