# Generated by Django 4.2 on 2023-05-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swan_page', '0004_alter_testimony_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
