# Generated by Django 4.2 on 2023-05-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swan_page', '0005_testimony_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
